# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    mkdir $(Build.ArtifactStagingDirectory)/publish
    npm install 
    cp -r node_modules server.js $(Build.ArtifactStagingDirectory)/publish
  displayName: 'Make artifacts ready'

- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)/publish'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: 'f4b641c1-99db-46d1-8110-5c6c24ce2fb9/7cf59834-72de-465b-849a-43b5ab6d856d'
    vstsFeedPackagePublish: 'user'
    versionOption: 'patch'
  displayName: 'Publish Artifacts'